title = "Screen configuration"

[monitors]

# The name of the top-level keys you can choose to your liking.
# It's a good idea to give each of them an anchor (e.g. &laptop) so that it can
# be referenced in other sections of the configuration
[monitors.laptop]
description = "Laptop"
# EDID is an identifier that is unique to each screen.  If you call `srandrd
# list` it will provide an overview of the connected screens with their EDIDs
edids = ["E430044600000000"]
# The path to a wallpaper can be specified for each screen.  The wallpaper is
# set through the tool "feh"
wallpaper = "~/wallpaper1920x1080.png"

[monitors.iiyama]
description = "Iiyama"
edids = ["CD2646B40000306A"]
wallpaper = "~/wallpaper1280x1024.png"
# The position of this screen relative to another screen, in this case
# relative to the screen with the "&laptop" anchor.  Position is one of
# right-of, left-of, above, below or same-as
reference_monitor = "monitors.laptop"
position = "left-of"

[monitors.benq]
description = "Benq BL1152"
edids = ["D109801B00005445"]
wallpaper = "~/wallpaper2560x1440.png"
reference_monitor = "monitors.laptop"
position = "left-of"

[monitors.benq.DP-1]

[monitors.benq.HDMI1]
reference_monitor = "monitors.benq.DP-1"
position = "left-of"
rotate = "left"
wallpaper = "~/wallpaper1440x2560.png"

[monitors.samsung]
description = "Samsung"
edids = ["2D4C03E800000000", "2D4C03E654573236"]
wallpaper = "~/wallpaper1920x1200.png"
reference_monitor = "monitors.laptop"
position = "left-of"

[monitors.dell]
description = "Dell"
edids = ["AC1040613239334C"]
wallpaper = "~/wallpaper1920x1080.png"
reference_monitor = "monitors.laptop"
position = "right-of"

[monitors.univentionbeamer]
description = "Acer"
edids = ["7204870100001893"]
wallpaper = "~/wallpaper1280x1024.png"
reference_monitor = "monitors.laptop"
position = "right-of"
# Resolution of this screen, either "auto" or a concrete resolution like
# "800x600"
resolution = "1280x1024"

# The default configuration that's applied if no other configuration matches.  A
# different section can be selected by setting the environment variable
# SCREENCONFIG_DEFAULT to the name of a different section.  This might be
# useful to use the same configuration file for multiple computers.  Put the
# following in your bashrc or window manager's start configuration
# export SCREENCONFIG_DEFAULT="monitors.fallback"
[monitors.fallback]
# edids = [] # edid is ignored because it's the fallback configuration
wallpaper = "~/wallpaper1920x1200.png"
reference_monitor = "monitors.laptop"
position = "right-of"
resolution = "auto"

